name: Publish Pub Dev & Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pub-dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
      - name: Check TAG Version
        run: |
          echo "TAG VERSION: $GITHUB_REF_NAME"
          echo "TAG VERSION: ${{  github.ref_name }}"
      - name: Publish To Pub Dev
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.PUB_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_REFRESH_TOKEN }}
          flutterBranch: 'flutter-3.27-candidate.0'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          
